export const verbFormsContent = {
  title: 'Verb Forms',
  sections: [
    {
      subtitle: 'Verb Forms পরিচিতি',
      content: 'Verb Forms হল ক্রিয়ার বিভিন্ন রূপ যা সময়, কর্তা, এবং ক্রিয়ার অবস্থা অনুসারে পরিবর্তিত হয়।',
      types: [
        'Base Form: মৌলিক ক্রিয়ার রূপ (go, eat, write)',
        'Present Participle: -ing এর সাথে ক্রিয়ার রূপ (going, eating, writing)',
        'Past Tense: গত সময়ের ক্রিয়ার রূপ (went, ate, wrote)',
        'Past Participle: সম্পন্ন অবস্থার ক্রিয়ার রূপ (gone, eaten, written)'
      ]
    },
    {
      subtitle: 'Regular or Weak Verb Forms',
      content: 'Regular Verb-এর Verb Forms সহজে তৈরি হয়:',
      examples: [
        'Base Form: play',
        'Present Participle: playing',
        'Past Tense: played',
        'Past Participle: played'
      ]
    },
    {
      subtitle: 'Irregular or Strong Verb Forms',
      content: 'Irregular Verb-এর Verb Forms আলাদা নিয়মে তৈরি হয়:',
      examples: [
        'Base Form: go, eat, write',
        'Present Participle: going, eating, writing',
        'Past Tense: went, ate, wrote',
        'Past Participle: gone, eaten, written'
      ]
    },
    {
      subtitle: 'Verb Forms-এর ব্যবহার',
      content: 'Verb Forms বিভিন্ন Tense এবং Context-এ ব্যবহৃত হয়:',
      examples: [
        'Simple Present: I play cricket. (Base Form)',
        'Present Continuous: I am playing cricket. (Present Participle)',
        'Simple Past: I played cricket yesterday. (Past Tense)',
        'Present Perfect: I have played cricket. (Past Participle)'
      ]
    },
    {
      subtitle: 'Some Strong Verb Forms',
      content: 'Base Form (V1) • Past (V2) • Past Participle (V3)',
      examples: [
        'Arise • arose • arisen',
        'Be • was/were • been',
        'Begin • began • begun',
        'Break • broke • broken',
        'Bring • brought • brought',
        'Build • built • built',
        'Buy • bought • bought',
        'Choose • chose • chosen',
        'Come • came • come',
        'Do • did • done',
        'Draw • drew • drawn',
        'Drink • drank • drunk',
        'Drive • drove • driven',
        'Eat • ate • eaten',
        'Fall • fell • fallen',
        'Fight • fought • fought',
        'Find • found • found',
        'Fly • flew • flown',
        'Forget • forgot • forgotten',
        'Get • got • gotten',
        'Give • gave • given',
        'Go • went • gone',
        'Grow • grew • grown',
        'Have • had • had',
        'Hear • heard • heard',
        'Hide • hid • hidden',
        'Know • knew • known',
        'Learn • learned/learnt • learned/learnt',
        'Leave • left • left',
        'Lose • lost • lost',
        'Make • made • made',
        'Meet • met • met',
        'Pay • paid • paid',
        'Read • read • read',
        'Ride • rode • ridden',
        'Ring • rang • rung',
        'Rise • rose • risen',
        'Run • ran • run',
        'Say • said • said',
        'See • saw • seen',
        'Sell • sold • sold',
        'Send • sent • sent',
        'Sing • sang • sung',
        'Sit • sat • sat',
        'Sleep • slept • slept',
        'Speak • spoke • spoken',
        'Stand • stood • stood',
        'Steal • stole • stolen',
        'Swim • swam • swum',
        'Take • took • taken',
        'Teach • taught • taught',
        'Tell • told • told',
        'Think • thought • thought',
        'Throw • threw • thrown',
        'Understand • understood • understood',
        'Wake • woke • woken',
        'Wear • wore • worn',
        'Win • won • won',
        'Write • wrote • written'
      ]
    },
    {
      subtitle: 'Some Weak Verb Forms',
      content: 'Base Form (V1) • Past (V2) • Past Participle (V3)',
      examples: [
        'Add • added • added',
        'Ask • asked • asked',
        'Call • called • called',
        'Clean • cleaned • cleaned',
        'Close • closed • closed',
        'Cook • cooked • cooked',
        'Create • created • created',
        'Dance • danced • danced',
        'End • ended • ended',
        'Finish • finished • finished',
        'Help • helped • helped',
        'Jump • jumped • jumped',
        'Kiss • kissed • kissed',
        'Learn • learned • learned',
        'Like • liked • liked',
        'Listen • listened • listened',
        'Love • loved • loved',
        'Move • moved • moved',
        'Open • opened • opened',
        'Play • played • played',
        'Push • pushed • pushed',
        'Reach • reached • reached',
        'Receive • received • received',
        'Remain • remained • remained',
        'Repair • repaired • repaired',
        'Return • returned • returned',
        'Save • saved • saved',
        'Start • started • started',
        'Stay • stayed • stayed',
        'Stop • stopped • stopped',
        'Talk • talked • talked',
        'Travel • traveled • traveled',
        'Try • tried • tried',
        'Turn • turned • turned',
        'Use • used • used',
        'Walk • walked • walked',
        'Want • wanted • wanted',
        'Watch • watched • watched',
        'Work • worked • worked'
      ]
    }
  ]
};
